version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M3_HOME=C:\maven\apache-maven-3.5.2
  - cmd: SET M3=%M3_HOME%\bin
  - cmd: SET PATH=%M3%;%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn clean package --batch-mode -DskipTests
test_script:
  - mvn clean test --batch-mode -Djna.nosys=true
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
