version: '{build}'
os: Windows Server 2012
image:
  - Visual Studio 2017
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      Copy-Item appveyor.settings.xml C:\Users\appveyor\.m2\settings.xml
  - cmd: SET M3_HOME=C:\maven\apache-maven-3.5.0
  - cmd: SET M3=%M3_HOME%\bin
  - cmd: SET PATH=%M3%;%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn clean package --batch-mode -DskipTests
test_script:
  - mvn clean test --batch-mode -Djna.nosys=true
deploy_script:
  - mvn clean deploy --batch-mode -DskipTests
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2